# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flog < Formula
  desc "Fast Log Filter - A blazingly fast CLI tool for filtering structured logs"
  homepage "https://github.com/ishk9/flog"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ishk9/flog/releases/download/v0.1.0/flog_0.1.0_darwin_amd64.tar.gz"
      sha256 "9c950e1163aa824ed324312c5d464852a8df210bf6b1fb491a4d8c96ebbdd6a0"

      def install
        bin.install "flog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ishk9/flog/releases/download/v0.1.0/flog_0.1.0_darwin_arm64.tar.gz"
      sha256 "3eb85c25a076371e60939a979c8745cd6e4adffd7e48e75dcb0389427adf7f15"

      def install
        bin.install "flog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ishk9/flog/releases/download/v0.1.0/flog_0.1.0_linux_amd64.tar.gz"
      sha256 "342f06d2bda0bae64ff2ba2b8ebc9849e9ad58979996fe608deb641f0edb51da"
      def install
        bin.install "flog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ishk9/flog/releases/download/v0.1.0/flog_0.1.0_linux_arm64.tar.gz"
      sha256 "dee2b0c05f5800182f6e2cc113249a687197988e3f9839b028dda34534495196"
      def install
        bin.install "flog"
      end
    end
  end

  test do
    system "#{bin}/flog", "--version"
  end
end
